# Generated by Django 5.2.7 on 2025-10-23 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField()),
                ('merkle_root', models.CharField(blank=True, max_length=64)),
                ('itemsExist', models.BinaryField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
