# Generated by Django 5.2.7 on 2025-10-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_data_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='image_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='block',
            name='registered_image',
            field=models.ImageField(blank=True, null=True, upload_to='registered_images/'),
        ),
    ]
