# Generated by Django 5.2.7 on 2025-12-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_block_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='ai_consent',
            field=models.BooleanField(default=False, help_text='Do you consent to AI training on this image?'),
        ),
        migrations.AddField(
            model_name='block',
            name='legal_name',
            field=models.CharField(default='Unknown', help_text='Full Legal Name of the Rights Holder', max_length=255),
            preserve_default=False,
        ),
    ]
