# Generated by Django 5.2.7 on 2025-12-03 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_block_ai_consent_block_legal_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='perceptual_hash',
            field=models.CharField(blank=True, help_text='pHash for similarity search', max_length=64, null=True),
        ),
    ]
